targets:
  WeatherMate:
    sources:
      - ../src/WeatherMate
    platform: iOS
    type: application
    scheme:
      environmentVariables:
        - variable: OS_ACTIVITY_MODE
          value: disable
          isEnabled: false
    settings:
      base:
        FRAMEWORK_SEARCH_PATHS: $(PROJECT_DIR)
      group: [app]
    dependencies:
      - target: WM_SDK
      - target: WM_API
    # prebuildScripts:
    #   - name: SwiftGen
    #     script: scripts/swiftgen.sh WeatherMate
    postbuildScripts:
      - name: Format Code
        script: scripts/format-code.sh src/WeatherMate
      - name: Reveal
        script: scripts/reveal.sh
