targets:
  WM_SDK:
    sources: ../src/WM_SDK
    platform: iOS
    type: framework
    dependencies:
      - target: WM_API
    postbuildScripts:
      - name: Format Code
        script: scripts/format-code.sh src/WM_SDK
  WM_API:
    sources: ../src/WM_API
    platform: iOS
    type: framework
    settings:
      base:
        FRAMEWORK_SEARCH_PATHS: $(PROJECT_DIR)
    dependencies:
      - carthage: Alamofire
