targets:
  WM_SDK:
    sources: ../src/WM_SDK
    platform: iOS
    type: framework
  WM_API:
    sources: ../src/WM_API
    platform: iOS
    type: framework
    dependencies:
      - carthage: Alamofire
