name: WeatherMate
settingGroups:
  app:
    base:
      APP_NAME: WeatherMate
      PRODUCT_BUNDLE_IDENTIFIER: co.leo.wang.weathermate
      DEVELOPMENT_TEAM: C5745B5785
      APP_GROUP: group.co.leo.wang
      CODE_SIGN_STYLE: Automatic
options:
   bundleIdPrefix: co.leo.wang
   carthageExecutablePath: ./mint run carthage carthage
   deploymentTarget:
    iOS: 10.0
    tvOS: 10.0