name: WeatherMate
settings:
  OTHER_SWIFT_FLAGS: $(inherited) -Xfrontend -warn-long-expression-type-checking=500 -Xfrontend -warn-long-function-bodies=500
  CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES # Silence project warning
settingGroups:
  app:
    base:
      APP_NAME: WeatherMate
      PRODUCT_BUNDLE_IDENTIFIER: co.leo.wang.weathermate
      DEVELOPMENT_TEAM: C5745B5785
      APP_GROUP: group.co.leo.wang
      CODE_SIGN_STYLE: Automatic
options:
   bundleIdPrefix: co.leo.wang
   carthageExecutablePath: ./mint run carthage carthage
   deploymentTarget:
    iOS: 10.0
    tvOS: 10.0