openapi: 3.0.0
info:
  title: Weather Mate
  version: 1.0.0
  description: This spec is constructed based on OpenWeatherMap API data structure.
  termsOfService:
    - https://openweathermap.org
    - https://agromonitoring.com
    - https://openweather.co.uk/
    - https://owm.io
  contact:
    email: wangqingzhouleo@gmail.com
    name: Leo Wang
servers:
  - url: api.openweathermap.org/data/{version}
    description: The main end point for weather data.
    variables:
      version:
        enum:
          - '2.5'
          - '3.0'
        default: '2.5'
  # - url: maps.openweathermap.org/maps
  #   description: Weather map
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: appid
      in: query
  schemas:
    Coord:
      type: object
      properties:
        lon:
          type: number
          format: double
        lat:
          type: number
          format: double