//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class City: APIModel {

    /** City ID */
    public var id: Int

    /** City name */
    public var name: String

    public var coord: Coord

    public var country: String

    public init(id: Int, name: String, coord: Coord, country: String) {
        self.id = id
        self.name = name
        self.coord = coord
        self.country = country
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        id = try container.decode("id")
        name = try container.decode("name")
        coord = try container.decode("coord")
        country = try container.decode("country")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(id, forKey: "id")
        try container.encode(name, forKey: "name")
        try container.encode(coord, forKey: "coord")
        try container.encode(country, forKey: "country")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? City else { return false }
      guard self.id == object.id else { return false }
      guard self.name == object.name else { return false }
      guard self.coord == object.coord else { return false }
      guard self.country == object.country else { return false }
      return true
    }

    public static func == (lhs: City, rhs: City) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
