//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class Clouds: APIModel {

    /** Cloudiness, % */
    public var all: Double?

    public init(all: Double? = nil) {
        self.all = all
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        all = try container.decodeIfPresent("all")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(all, forKey: "all")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? Clouds else { return false }
      guard self.all == object.all else { return false }
      return true
    }

    public static func == (lhs: Clouds, rhs: Clouds) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
