//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class DailyForecast: ForecastSummary {

    public var list: [DailyWeathertItem]

    public init(list: [DailyWeathertItem], city: City? = nil, cnt: Int? = nil, cod: String? = nil, message: Double? = nil) {
        self.list = list
        super.init(city: city, cnt: cnt, cod: cod, message: message)
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        list = try container.decodeArray("list")
        try super.init(from: decoder)
    }

    public override func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(list, forKey: "list")
        try super.encode(to: encoder)
    }

    override public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? DailyForecast else { return false }
      guard self.list == object.list else { return false }
      return super.isEqual(to: object)
    }
}
