//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class Rain: APIModel {

    /** Rain volume for the last 1 hour, mm */
    public var _1h: Double?

    /** Rain volume for the last 3 hours, mm */
    public var _3h: Double?

    public init(_1h: Double? = nil, _3h: Double? = nil) {
        self._1h = _1h
        self._3h = _3h
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        _1h = try container.decodeIfPresent("1h")
        _3h = try container.decodeIfPresent("3h")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(_1h, forKey: "1h")
        try container.encodeIfPresent(_3h, forKey: "3h")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? Rain else { return false }
      guard self._1h == object._1h else { return false }
      guard self._3h == object._3h else { return false }
      return true
    }

    public static func == (lhs: Rain, rhs: Rain) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
