//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class Wind: APIModel {

    /** Wind direction, degrees (meteorological) */
    public var deg: Double?

    /** Wind speed. Unit Default: meter/sec, Metric: meter/sec, Imperial: miles/hour. */
    public var speed: Double?

    public init(deg: Double? = nil, speed: Double? = nil) {
        self.deg = deg
        self.speed = speed
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        deg = try container.decodeIfPresent("deg")
        speed = try container.decodeIfPresent("speed")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(deg, forKey: "deg")
        try container.encodeIfPresent(speed, forKey: "speed")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? Wind else { return false }
      guard self.deg == object.deg else { return false }
      guard self.speed == object.speed else { return false }
      return true
    }

    public static func == (lhs: Wind, rhs: Wind) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
