//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** This spec is constructed based on OpenWeatherMap API data structure. */
public struct WMAPI {

    /// Whether to discard any errors when decoding optional properties
    public static var safeOptionalDecoding = false

    /// Whether to remove invalid elements instead of throwing when decoding arrays
    public static var safeArrayDecoding = false

    /// Used to encode Dates when uses as string params
    public static let dateEncodingFormatter = DateFormatter(formatString: "yyyy-MM-dd'T'HH:mm:ssZZZZZ")

    public static let version = "1.0.0"

    public enum Forecast {}
    public enum Weather {}

    public enum Server {

        public static let data = "https://api.openweathermap.org/data/2.5"

        public static let maps = "http://maps.openweathermap.org/maps/2.0"
    }
}
